[project]
name = "badrat"
version = "0.0.1"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "baml-py>=0.71.1",
    "fastapi[standard]>=0.115.6",
]

[tool.basedpyright]
typeCheckingMode = "standard"
